// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npmvwiyzfwklzffwvojt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbXZ3aXl6ZndrbHpmZnd2b2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjY5MTAsImV4cCI6MjA2NzQwMjkxMH0.NWwA-xw1msRQXfCfCXaxxeXZY4odTvhysKj4EJgcz2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});